name: MariaNet


services:
  marianet-postgres:
    image: postgres:17-alpine
    init: true
    restart: unless-stopped
    stop_grace_period: 30s

    env_file:
      - .env.compose

    secrets:
      - db_password

    volumes:
      - psql_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - marianet-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  migrations:
    build:
      context: .
      dockerfile: Dockerfile

    command: alembic upgrade head

    env_file:
      - .env.compose

    secrets:
      - db_password

    depends_on:
      marianet-postgres:
        condition: service_healthy

    networks:
      - marianet-network

    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: marianet_server
    command: flask --app src.myapp.run run --host=0.0.0.0

    ports:
      - "5000:5000/tcp"

    env_file:
      - .env.compose
    
    secrets:
      - db_password

    depends_on:
      marianet-postgres:
        condition: service_healthy
    
    networks:
      - marianet-network
    
    restart: unless-stopped
    stop_grace_period: 30s

volumes:
  psql_data:

networks:
  marianet-network:
    driver: bridge 

secrets:
  db_password:
    file: ./secrets/db_password.txt
