"""Initial migration. Tables users, games, moves.

Revision ID: 60a64feeb804
Revises: 
Create Date: 2026-07-29 21:42:23.903942

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60a64feeb804"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("username", sa.String(length=30), nullable=False),
    sa.Column("email", sa.String(length=30), nullable=False),
    sa.Column("password_hash", sa.String(length=500), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("id"),
    sa.UniqueConstraint("username"),
    )
    op.create_table("games",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("status", sa.Enum("ACTIVE", "FINISHED", "ABANDONED", name="gamestatus"), nullable=False),
    sa.Column("result", sa.Enum("WHITE_WIN", "BLACK_WIN", "DRAW", "UNKNOWN", name="gameresult"), nullable=False),
    sa.Column("fen_start", sa.String(length=100), nullable=True),
    sa.Column("fen_current", sa.String(length=100), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("finished_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    )
    op.create_table("moves",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("game_id", sa.Integer(), nullable=True),
    sa.Column("move_number", sa.Integer(), nullable=True),
    sa.Column("played_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["game_id"], ["games.id"] ),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"] ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moves")
    op.drop_table("games")
    op.drop_table("users")
    # ### end Alembic commands ###
